# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  gradrole-app:
    image: gradrole
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true

      - SPRING_DATASOURCE_URL=jdbc:postgresql://gradrole-postgresql:5432/gradrole
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://gradrole-postgresql:5432/gradrole
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  gradrole-postgresql:
    image: postgres:13.1
    # volumes:
    #     - ~/volumes/jhipster/gradrole/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gradrole
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
