version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gradrole
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gradrole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
